---
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: trailing-whitespace
-   repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
    -   id: yamlfmt
        args:
        -   --mapping
        -   '4'
        -   --sequence
        -   '4'
        -   --offset
        -   '0'
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.0
    hooks:
    -   id: black
ci:
    autoupdate_commit_msg: 'chore: update pre-commit hooks'
    autoupdate_schedule: quarterly
    autofix_commit_msg: 'style: pre-commit fixes'
